--CREATE DATABASE PRUEBAS
--GO
--USE TAREAS

CREATE TABLE COLABORADOR
(
	COLABORADOR_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRE VARCHAR(255)
)

CREATE TABLE TAREAS
(
	TAREAS_ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TAREAS_DESCRIPCION VARCHAR(255),
	TAREAS_ESTADO VARCHAR(255),
	TAREAS_PRIORIDAD VARCHAR(255),
	TAREAS_FECHA_INICIO VARCHAR(255),
	TAREA_FECHA_FIN VARCHAR(255),
	TAREAS_NOTAS VARCHAR(255),
	TAREAS_COLABORADOR INT FOREIGN KEY REFERENCES COLABORADOR(COLABORADOR_ID)
)

-------Store procedures-------------------------------------------------------------------------------------------
GO

CREATE PROCEDURE PA_LIST_COLABORADORES
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		C.COLABORADOR_ID,
		C.NOMBRE
		FROM COLABORADOR AS C
	SET NOCOUNT OFF
END

GO

CREATE PROCEDURE PA_LIST_TAREAS
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		TA.TAREAS_ID,
		TA.TAREAS_DESCRIPCION,
		TA.TAREAS_ESTADO,
		TA.TAREAS_PRIORIDAD,
		TA.TAREAS_FECHA_INICIO,
		TA.TAREA_FECHA_FIN,
		TA.TAREAS_NOTAS,
		C.COLABORADOR_ID,
		C.NOMBRE
		FROM  TAREAS AS TA
		JOIN COLABORADOR AS C ON C.COLABORADOR_ID = TA.TAREAS_COLABORADOR
	SET NOCOUNT OFF
END


GO

CREATE PROCEDURE PA_LIST_TAREAS_ID
@TAREAS_ID INT
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		TA.TAREAS_ID,
		TA.TAREAS_DESCRIPCION,
		TA.TAREAS_ESTADO,
		TA.TAREAS_PRIORIDAD,
		TA.TAREAS_FECHA_INICIO,
		TA.TAREA_FECHA_FIN,
		TA.TAREAS_NOTAS,
	    C.COLABORADOR_ID,
		C.NOMBRE
		FROM  TAREAS AS TA
		JOIN COLABORADOR AS C ON C.COLABORADOR_ID = TA.TAREAS_COLABORADOR
		WHERE TA.TAREAS_ID = @TAREAS_ID
	SET NOCOUNT OFF
END


GO

CREATE PROCEDURE PA_LIST_TAREAS_COLABORADOR
@COLABORADOR_ID INT
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		TA.TAREAS_ID,
		TA.TAREAS_DESCRIPCION,
		TA.TAREAS_ESTADO,
		TA.TAREAS_PRIORIDAD,
		TA.TAREAS_FECHA_INICIO,
		TA.TAREA_FECHA_FIN,
		TA.TAREAS_NOTAS
		FROM  TAREAS AS TA
		JOIN COLABORADOR AS C ON C.COLABORADOR_ID = TA.TAREAS_COLABORADOR
		WHERE TA.TAREAS_COLABORADOR = @COLABORADOR_ID
	SET NOCOUNT OFF
END

GO

CREATE PROCEDURE PA_LIST_TAREAS_ESTADO
@ESTADO VARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		TA.TAREAS_ID,
		TA.TAREAS_DESCRIPCION,
		TA.TAREAS_ESTADO,
		TA.TAREAS_PRIORIDAD,
		TA.TAREAS_FECHA_INICIO,
		TA.TAREA_FECHA_FIN,
		TA.TAREAS_NOTAS
		FROM  TAREAS AS TA
		JOIN COLABORADOR AS C ON C.COLABORADOR_ID = TA.TAREAS_COLABORADOR
		WHERE TA.TAREAS_COLABORADOR = @ESTADO
	SET NOCOUNT OFF
END

GO

CREATE PROCEDURE PA_LIST_TAREAS_PRIORIDAD
@PRIORIDAD VARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		TA.TAREAS_ID,
		TA.TAREAS_DESCRIPCION,
		TA.TAREAS_ESTADO,
		TA.TAREAS_PRIORIDAD,
		TA.TAREAS_FECHA_INICIO,
		TA.TAREA_FECHA_FIN,
		TA.TAREAS_NOTAS
		FROM  TAREAS AS TA
		JOIN COLABORADOR AS C ON C.COLABORADOR_ID = TA.TAREAS_COLABORADOR
		WHERE TA.TAREAS_COLABORADOR = @PRIORIDAD
	SET NOCOUNT OFF
END

GO

CREATE PROCEDURE PA_LIST_TAREAS_FECHAS
@FECHAS VARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON
		SELECT 
		TA.TAREAS_ID,
		TA.TAREAS_DESCRIPCION,
		TA.TAREAS_ESTADO,
		TA.TAREAS_PRIORIDAD,
		TA.TAREAS_FECHA_INICIO,
		TA.TAREA_FECHA_FIN,
		TA.TAREAS_NOTAS
		FROM  TAREAS AS TA
		JOIN COLABORADOR AS C ON C.COLABORADOR_ID = TA.TAREAS_COLABORADOR
		WHERE TA.TAREAS_COLABORADOR = @FECHAS
	SET NOCOUNT OFF
END

GO

CREATE PROCEDURE PA_CREATE_TAREA

	@TAREAS_DESCRIPCION VARCHAR(255),
	@TAREAS_ESTADO VARCHAR(255),
	@TAREAS_PRIORIDAD VARCHAR(255),
	@TAREAS_FECHA_INICIO VARCHAR(255),
	@TAREA_FECHA_FIN VARCHAR(255),
	@TAREAS_NOTAS VARCHAR(255),
	@TAREAS_COLABORADOR INT
AS
BEGIN
BEGIN TRANSACTION 
	INSERT INTO TAREAS VALUES(@TAREAS_DESCRIPCION,
							  @TAREAS_ESTADO,
							  @TAREAS_PRIORIDAD,
							  @TAREAS_FECHA_INICIO,
							  @TAREA_FECHA_FIN,
							  @TAREAS_NOTAS,
							  @TAREAS_COLABORADOR)
IF @@ERROR <> 0 
	ROLLBACK TRANSACTION 
	ELSE 
	COMMIT TRANSACTION
END

GO

CREATE PROCEDURE PA_DELETE_TAREA
@TAREAS_ID INT
AS
BEGIN
	BEGIN TRANSACTION
		DELETE TAREAS WHERE TAREAS_ESTADO != 'EN PROCESO' AND TAREAS_ID = @TAREAS_ID
	IF @@ERROR <> 0 
	ROLLBACK TRANSACTION 
	ELSE 
	COMMIT TRANSACTION
END
GO

CREATE PROCEDURE PA_UPDATE_TAREA
	@TAREAS_ID INT,
	@TAREAS_DESCRIPCION VARCHAR(255),
	@TAREAS_ESTADO VARCHAR(255),
	@TAREAS_PRIORIDAD VARCHAR(255),
	@TAREAS_FECHA_INICIO VARCHAR(255),
	@TAREA_FECHA_FIN VARCHAR(255),
	@TAREAS_NOTAS VARCHAR(255),
	@TAREAS_COLABORADOR INT
AS
BEGIN
BEGIN TRANSACTION 
	UPDATE TAREAS SET TAREAS_DESCRIPCION = @TAREAS_DESCRIPCION,
					  TAREAS_ESTADO = @TAREAS_ESTADO,
					  TAREAS_PRIORIDAD = @TAREAS_PRIORIDAD,
					  TAREAS_FECHA_INICIO = @TAREAS_FECHA_INICIO,
					  TAREA_FECHA_FIN = @TAREA_FECHA_FIN,
					  TAREAS_NOTAS = @TAREAS_NOTAS,
					  TAREAS_COLABORADOR = @TAREAS_COLABORADOR
					  WHERE TAREAS_ID = @TAREAS_ID AND TAREAS_ESTADO != 'FINALIZADA'
IF @@ERROR <> 0 
	ROLLBACK TRANSACTION 
	ELSE 
	COMMIT TRANSACTION
END